############################
## Sampling Rules Config ##
############################

# Please refer the operators from https://github.com/honeycombio/refinery/blob/76b9477076953faf57cadcad0f349e1616b20751/sample/rules.go#L76

# DryRun - If enabled, marks traces that would be dropped given current sampling rules,
# and sends all traces regardless
DryRun = $DRY_RUN
SampleRate = 1

[dev]
  Sampler = "RulesBasedSampler"
  # 'dev.rule' is how you specify an environment-wide rule
  # This drops all healthchecks across an environment.
  [[dev.rule]]
    name = "drop healthchecks"
    drop = true
    [[dev.rule.condition]]
      field = "http.route"
      operator = "="
      value = "/health"

  # This keeps all 500 errors across an environment.
  [[dev.rule]]
    name = "keep 500 errors"
    SampleRate = 1
    [[dev.rule.condition]]
      field = "http.status_code"
      operator = ">="
      value = 500

  [[dev.rule]]
    name = "keep all registrations"
    SampleRate = 1
    [[dev.rule.condition]]
      field = "http.route"
      operator = "="
      value = "/api/v0/user/register"

  [[dev.rule]]
    name = "dynamically sample all logins"
    [[dev.rule.condition]]
      field = "http.route"
      operator = "="
      value = "/api/v0/user/login"
    [dev.rule.sampler.EMADynamicSampler]
      Sampler = "EMADynamicSampler"
      AddSampleRateKeyToTrace = true
      AddSampleRateKeyToTraceField = "meta.refinery.dynsampler.logins"
      FieldList = ["http.status_code", "readz.login.user_id"]
      GoalSampleRate = 50
    
  # This dynamically samples all 200 responses across an environment.
  [[dev.rule]]
    name = "dynamically sample stories created by users"
    [[dev.rule.condition]]
      field = "status_code"
      operator = "="
      value = 201
    [[dev.rule.conditions]]
      field = "http.route"
      operator = "="
      value = "/api/v0/write/<story_type>"
    [dev.rule.sampler.EMADynamicSampler]
      Sampler = "EMADynamicSampler"
      AddSampleRateKeyToTrace = true
      AddSampleRateKeyToTraceField = "meta.refinery.dynsampler.200s"
      FieldList = ["http.target", "readz.post_story.user_id"]
      GoalSampleRate = 15

  # This dynamically samples all 200 responses across an environment.
  [[dev.rule]]
    name = "dynamically sample 200 responses"
    [[dev.rule.condition]]
      field = "status_code"
      operator = "<="
      value = 299
    [dev.rule.sampler.EMADynamicSampler]
      Sampler = "EMADynamicSampler"
      AddSampleRateKeyToTrace = true
      AddSampleRateKeyToTraceField = "meta.refinery.dynsampler.200s"
      FieldList = ["http.target"]
      GoalSampleRate = 15

  [[dev.rule]]
    SampleRate = 10 # default when no rules match, if missing defaults to 10
