############################
## Sampling Rules Config ##
############################

# Please refer the operators from https://github.com/honeycombio/refinery/blob/76b9477076953faf57cadcad0f349e1616b20751/sample/rules.go#L76

# DryRun - If enabled, marks traces that would be dropped given current sampling rules,
# and sends all traces regardless
DryRun = $DRY_RUN
SampleRate = 1

[dev]
  Sampler = "RulesBasedSampler"
  # 'dev.rule' is how you specify an environment-wide rule
  # This drops all healthchecks across an environment.
  [[dev.rule]]
    name = "drop newrelic checks"
    drop = true
    [[dev.rule.condition]]
      field = "http.target"
      operator = "contains"
      value = "/agent"

  # This keeps all 500 errors across an environment.
  [[dev.rule]]
    name = "keep 500 errors"
    SampleRate = 1
    [[dev.rule.condition]]
      field = "http.status_code"
      operator = ">="
      value = 500

  [[dev.rule]]
    name = "keep all registrations"
    SampleRate = 1
    [[dev.rule.condition]]
      field = "http.route"
      operator = "contains"
      value = "/signup"

  [[dev.rule]]
    name = "keep all logins"
    SampleRate = 1
    [[dev.rule.condition]]
      field = "http.route"
      operator = "contains"
      value = "/login"

  # This dynamically samples all 200 responses across an environment.
  [[dev.rule]]
    name = "dynamically sample 200 responses"
    [[dev.rule.condition]]
      field = "status_code"
      operator = "<="
      value = 299
    [dev.rule.sampler.EMADynamicSampler]
      Sampler = "EMADynamicSampler"
      AddSampleRateKeyToTrace = true
      AddSampleRateKeyToTraceField = "meta.refinery.dynsampler.200s"
      FieldList = ["http.target"]
      GoalSampleRate = 15

  [[dev.rule]]
    SampleRate = 10 # default when no rules match, if missing defaults to 10
